apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml --namespace=hoeeeeeh --controller statefulset convert
    kompose.version: 1.31.0 (a04ecdb9e)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
  namespace: hoeeeeeh
spec:
  clusterIP: None
  ports:
    - name: "6002"
      port: 6002
      targetPort: 6002
  selector:
    io.kompose.service: backend
  type: ClusterIP
status:
  loadBalancer: {}
