apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml --namespace=hoeeeeeh --controller statefulset convert
    kompose.version: 1.31.0 (a04ecdb9e)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
  namespace: hoeeeeeh
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  serviceName: backend
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/receipt-normalization-receipt: "true"
        io.kompose.service: backend
    spec:
      containers:
        - image: kuploy/receipt-backend
          name: receipt-backend
          ports:
            - containerPort: 6002
              hostPort: 6002
              protocol: TCP
          resources: {}
      restartPolicy: Always
  updateStrategy: {}
status:
  availableReplicas: 0
  replicas: 0
