apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml --namespace=hoeeeeeh --controller statefulset convert
    kompose.version: 1.31.0 (a04ecdb9e)
  creationTimestamp: null
  labels:
    io.kompose.service: front
  name: front
  namespace: hoeeeeeh
spec:
  clusterIP: None
  ports:
    - name: "6001"
      port: 6001
      targetPort: 6001
  selector:
    io.kompose.service: front
  type: ClusterIP
status:
  loadBalancer: {}
